version: '3'
services:
  webapp:
    image: nginx
    networks:
      net_name:
        ipv4_address: 192.168.1.101

networks:
  net_name:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
